name: gitter
description: Library to use the Gitter api
version: 0.1.2
homepage: https://github.com/dart-flitter/gitter_dart
authors:
  - Kevin Segaud <segaud.kevin@gmail.com>
  - Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=1.20.1 <2.1.0'

dependencies:
  http: ^0.11.3+13

